.TH "com.video_browser_thesis.json.JSONParser" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.json.JSONParser \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "JSONObject \fBgetJSONFromUrl\fP (String url)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creates a JSON object from the data retrieved from the provided url 
.PP
\fBAuthor:\fP
.RS 4
Anshul Saini 
.RE
.PP
\fBVersion:\fP
.RS 4
5
.RE
.PP
\fBParameters:\fP
.RS 4
\fIis\fP 
.br
\fIjObj\fP JSON Object which is finally created from the JSON string 
.br
\fIjson\fP JSON String which is used to create JSON Object 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBSee Also:\fP
.RS 4
.RE
.PP

.PP
Definition at line 48 of file JSONParser\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "JSONObject com\&.video_browser_thesis\&.json\&.JSONParser\&.getJSONFromUrl (Stringurl)"
Makes the HTTP request, parses the JSON String, creates and JSON Object 
.PP
\fBParameters:\fP
.RS 4
\fIhttpClient\fP 
.br
\fIhttpPost\fP 
.br
\fIhttpResponse\fP 
.br
\fIhttpEntity\fP 
.br
\fIreader\fP 
.br
\fIsb\fP 
.br
\fIline\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
jObj 
.RE
.PP
\fBSee Also:\fP
.RS 4
JSONObject 
.RE
.PP

.PP
Definition at line 66 of file JSONParser\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
