.TH "com.video_browser_thesis.adapters.CircularListAdapter" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.adapters.CircularListAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseAdapter\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCircularListAdapter\fP (BaseAdapter listAdapter)"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "View \fBgetView\fP (int position, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "Object \fBgetItem\fP (int position)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int position)"
.br
.ti -1c
.RI "boolean \fBareAllItemsEnabled\fP ()"
.br
.ti -1c
.RI "int \fBgetItemViewType\fP (int position)"
.br
.ti -1c
.RI "int \fBgetViewTypeCount\fP ()"
.br
.ti -1c
.RI "boolean \fBisEmpty\fP ()"
.br
.ti -1c
.RI "boolean \fBisEnabled\fP (int position)"
.br
.ti -1c
.RI "void \fBnotifyDataSetChanged\fP ()"
.br
.ti -1c
.RI "void \fBnotifyDataSetInvalidated\fP ()"
.br
.ti -1c
.RI "View \fBgetDropDownView\fP (int position, View convertView, ViewGroup parent)"
.br
.ti -1c
.RI "boolean \fBhasStableIds\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constructs a  \fBCircularListAdapter\fP}\&.
.PP
\fBParameters:\fP
.RS 4
\fIlistAdapter\fP A \fBKeyframe_ListAdapter\fP that has to behave circular\&. 
.RE
.PP

.PP
Definition at line 27 of file CircularListAdapter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.CircularListAdapter (BaseAdapterlistAdapter)"

.PP
Definition at line 35 of file CircularListAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "boolean com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.areAllItemsEnabled ()"

.PP
Definition at line 65 of file CircularListAdapter\&.java\&.
.SS "int com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.getCount ()"

.PP
Definition at line 45 of file CircularListAdapter\&.java\&.
.SS "View com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.getDropDownView (intposition, ViewconvertView, ViewGroupparent)"

.PP
Definition at line 104 of file CircularListAdapter\&.java\&.
.SS "Object com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.getItem (intposition)"

.PP
Definition at line 55 of file CircularListAdapter\&.java\&.
.SS "long com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.getItemId (intposition)"

.PP
Definition at line 60 of file CircularListAdapter\&.java\&.
.SS "int com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.getItemViewType (intposition)"

.PP
Definition at line 70 of file CircularListAdapter\&.java\&.
.SS "View com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.getView (intposition, ViewconvertView, ViewGroupparent)"

.PP
Definition at line 50 of file CircularListAdapter\&.java\&.
.SS "int com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.getViewTypeCount ()"

.PP
Definition at line 75 of file CircularListAdapter\&.java\&.
.SS "boolean com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.hasStableIds ()"

.PP
Definition at line 110 of file CircularListAdapter\&.java\&.
.SS "boolean com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.isEmpty ()"

.PP
Definition at line 80 of file CircularListAdapter\&.java\&.
.SS "boolean com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.isEnabled (intposition)"

.PP
Definition at line 85 of file CircularListAdapter\&.java\&.
.SS "void com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.notifyDataSetChanged ()"

.PP
Definition at line 90 of file CircularListAdapter\&.java\&.
.SS "void com\&.video_browser_thesis\&.adapters\&.CircularListAdapter\&.notifyDataSetInvalidated ()"

.PP
Definition at line 98 of file CircularListAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
