.TH "com.video_browser_thesis.adapters.CrossBrowser_GalleryAdapter" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.adapters.CrossBrowser_GalleryAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseAdapter\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBViewHolder\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrossBrowser_GalleryAdapter\fP (Activity a, \fBKeyFrame_attributes\fP[] keyframe_attr)"
.br
.ti -1c
.RI "int \fBgetCount\fP ()"
.br
.ti -1c
.RI "Object \fBgetItem\fP (int position)"
.br
.ti -1c
.RI "long \fBgetItemId\fP (int position)"
.br
.ti -1c
.RI "View \fBgetView\fP (int position, View convertView, ViewGroup parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constructs a CrossBrowserGallery Video Adapter which extends a Base Adapter 
.PP
\fBAuthor:\fP
.RS 4
Anshul Saini 
.RE
.PP
\fBVersion:\fP
.RS 4
5 
.RE
.PP

.PP
Definition at line 37 of file CrossBrowser_GalleryAdapter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.video_browser_thesis\&.adapters\&.CrossBrowser_GalleryAdapter\&.CrossBrowser_GalleryAdapter (Activitya, \fBKeyFrame_attributes\fP[]keyframe_attr)"

.PP
Definition at line 43 of file CrossBrowser_GalleryAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "int com\&.video_browser_thesis\&.adapters\&.CrossBrowser_GalleryAdapter\&.getCount ()"

.PP
Definition at line 49 of file CrossBrowser_GalleryAdapter\&.java\&.
.SS "Object com\&.video_browser_thesis\&.adapters\&.CrossBrowser_GalleryAdapter\&.getItem (intposition)"

.PP
Definition at line 53 of file CrossBrowser_GalleryAdapter\&.java\&.
.SS "long com\&.video_browser_thesis\&.adapters\&.CrossBrowser_GalleryAdapter\&.getItemId (intposition)"

.PP
Definition at line 57 of file CrossBrowser_GalleryAdapter\&.java\&.
.SS "View com\&.video_browser_thesis\&.adapters\&.CrossBrowser_GalleryAdapter\&.getView (intposition, ViewconvertView, ViewGroupparent)"
Inflates the gallery item with different types of views\&. 
.PP
Definition at line 64 of file CrossBrowser_GalleryAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
