.TH "com.video_browser_thesis.activities.KeyframeListActivity" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.activities.KeyframeListActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCrossBrowser_btn_click\fP (View v)"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonHomeButtonClick\fP (View v)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Displays all the key frames of a video 
.PP
\fBAuthor:\fP
.RS 4
Anshul Saini 
.RE
.PP
\fBVersion:\fP
.RS 4
5 
.RE
.PP

.PP
Definition at line 40 of file KeyframeListActivity\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.video_browser_thesis\&.activities\&.KeyframeListActivity\&.onCreate (BundlesavedInstanceState)\fC [protected]\fP"
Setting the parameters for the reference frame
.PP
Definition at line 45 of file KeyframeListActivity\&.java\&.
.SS "void com\&.video_browser_thesis\&.activities\&.KeyframeListActivity\&.onCrossBrowser_btn_click (Viewv)"
Ends the current activity and returns to the previous activity 
.PP
Definition at line 97 of file KeyframeListActivity\&.java\&.
.SS "void com\&.video_browser_thesis\&.activities\&.KeyframeListActivity\&.onHomeButtonClick (Viewv)"
Ends the current activity and returns to the main activity 
.PP
Definition at line 117 of file KeyframeListActivity\&.java\&.
.SS "void com\&.video_browser_thesis\&.activities\&.KeyframeListActivity\&.onResume ()"
When the activity is resumed 
.PP
Definition at line 105 of file KeyframeListActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
