.TH "com.video_browser_thesis.activities.BuildConfig" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.activities.BuildConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final boolean \fBDEBUG\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file BuildConfig\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final boolean com\&.video_browser_thesis\&.activities\&.BuildConfig\&.DEBUG = true\fC [static]\fP"

.PP
Definition at line 5 of file BuildConfig\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
