.TH "com.video_browser_thesis.adapters" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.adapters \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCircularListAdapter\fP"
.br
.ti -1c
.RI "class \fBCrossBrowser_GalleryAdapter\fP"
.br
.ti -1c
.RI "class \fBCrossBrowser_ListAdapter\fP"
.br
.ti -1c
.RI "class \fBKeyframe_ListAdapter\fP"
.br
.ti -1c
.RI "class \fBMainGallery_VideoAdapter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
