.TH "com.video_browser_thesis.splashScreen.SplashScreen" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.splashScreen.SplashScreen \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "boolean \fB_active\fP = true"
.br
.ti -1c
.RI "int \fB_splashTime\fP = 3000"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main Splash Screen when the application is initiated
.PP
\fBParameters:\fP
.RS 4
\fI_active\fP Indicates if the splash screen is present 
.br
\fI_splashTime\fP The display time of the splash screen image in milliseconds 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBSee Also:\fP
.RS 4
Image 
.RE
.PP

.PP
Definition at line 38 of file SplashScreen\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.video_browser_thesis\&.splashScreen\&.SplashScreen\&.onCreate (BundlesavedInstanceState)"
Called when the activity is first created\&. Threads for displaying the splash screen
.PP
Definition at line 47 of file SplashScreen\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "boolean com\&.video_browser_thesis\&.splashScreen\&.SplashScreen\&._active = true\fC [protected]\fP"

.PP
Definition at line 40 of file SplashScreen\&.java\&.
.SS "int com\&.video_browser_thesis\&.splashScreen\&.SplashScreen\&._splashTime = 3000\fC [protected]\fP"

.PP
Definition at line 41 of file SplashScreen\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
