.TH "com.video_browser_thesis.activities.R" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.activities.R \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBattr\fP"
.br
.ti -1c
.RI "class \fBcolor\fP"
.br
.ti -1c
.RI "class \fBdimen\fP"
.br
.ti -1c
.RI "class \fBdrawable\fP"
.br
.ti -1c
.RI "class \fBid\fP"
.br
.ti -1c
.RI "class \fBlayout\fP"
.br
.ti -1c
.RI "class \fBstring\fP"
.br
.ti -1c
.RI "class \fBstyle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file R\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
