.TH "com.video_browser_thesis.elements.Video_attributes" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.elements.Video_attributes \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVideo_attributes\fP ()"
.br
.ti -1c
.RI "\fBVideo_attributes\fP (String \fBvideo_title\fP, String \fBvideo_author\fP, Bitmap \fBvideo_image\fP, String \fBtag_id\fP, String \fBvideo_id\fP, String \fBplayer_url\fP, String \fBlength\fP, String \fBtopics\fP, String \fBuploaded_time\fP, String \fBview_count\fP, String \fBdescription\fP, String \fBthumbnail\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBvideo_title\fP"
.br
.ti -1c
.RI "String \fBvideo_author\fP"
.br
.ti -1c
.RI "Bitmap \fBvideo_image\fP"
.br
.ti -1c
.RI "String \fBthumbnail\fP"
.br
.ti -1c
.RI "String \fBtag_id\fP"
.br
.ti -1c
.RI "String \fBvideo_id\fP"
.br
.ti -1c
.RI "String \fBplayer_url\fP"
.br
.ti -1c
.RI "String \fBlength\fP"
.br
.ti -1c
.RI "String \fBtopics\fP"
.br
.ti -1c
.RI "String \fBuploaded_time\fP"
.br
.ti -1c
.RI "String \fBview_count\fP"
.br
.ti -1c
.RI "String \fBdescription\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBVideo_attributes\fP 
.PP
\fBAuthor:\fP
.RS 4
Anshul Saini 
.RE
.PP
\fBVersion:\fP
.RS 4
5 
.RE
.PP

.PP
Definition at line 26 of file Video_attributes\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.video_browser_thesis\&.elements\&.Video_attributes\&.Video_attributes ()"

.PP
Definition at line 40 of file Video_attributes\&.java\&.
.SS "com\&.video_browser_thesis\&.elements\&.Video_attributes\&.Video_attributes (Stringvideo_title, Stringvideo_author, Bitmapvideo_image, Stringtag_id, Stringvideo_id, Stringplayer_url, Stringlength, Stringtopics, Stringuploaded_time, Stringview_count, Stringdescription, Stringthumbnail)"

.PP
Definition at line 44 of file Video_attributes\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.description"

.PP
Definition at line 38 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.length"

.PP
Definition at line 34 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.player_url"

.PP
Definition at line 33 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.tag_id"

.PP
Definition at line 31 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.thumbnail"

.PP
Definition at line 30 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.topics"

.PP
Definition at line 35 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.uploaded_time"

.PP
Definition at line 36 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.video_author"

.PP
Definition at line 28 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.video_id"

.PP
Definition at line 32 of file Video_attributes\&.java\&.
.SS "Bitmap com\&.video_browser_thesis\&.elements\&.Video_attributes\&.video_image"

.PP
Definition at line 29 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.video_title"

.PP
Definition at line 27 of file Video_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.Video_attributes\&.view_count"

.PP
Definition at line 37 of file Video_attributes\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
