.TH "com.video_browser_thesis.elements.KeyFrame_attributes" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.elements.KeyFrame_attributes \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyFrame_attributes\fP (String \fBimage_source\fP, String \fBframe_point\fP, Bitmap \fBvideo_img\fP)"
.br
.ti -1c
.RI "void \fBsetBackgroundColor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBimage_source\fP"
.br
.ti -1c
.RI "String \fBframe_point\fP"
.br
.ti -1c
.RI "Bitmap \fBvideo_img\fP"
.br
.ti -1c
.RI "int \fBbackground_color\fP = Color\&.TRANSPARENT"
.br
.in -1c
.SH "Detailed Description"
.PP 
KeyFrame attributes 
.PP
\fBAuthor:\fP
.RS 4
Anshul Saini 
.RE
.PP
\fBVersion:\fP
.RS 4
5 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIimage_source\fP 
.br
\fIframe_point\fP 
.br
\fIvideo_img\fP 
.RE
.PP

.PP
Definition at line 34 of file KeyFrame_attributes\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.video_browser_thesis\&.elements\&.KeyFrame_attributes\&.KeyFrame_attributes (Stringimage_source, Stringframe_point, Bitmapvideo_img)"

.PP
Definition at line 40 of file KeyFrame_attributes\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.video_browser_thesis\&.elements\&.KeyFrame_attributes\&.setBackgroundColor ()"

.PP
Definition at line 46 of file KeyFrame_attributes\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "int com\&.video_browser_thesis\&.elements\&.KeyFrame_attributes\&.background_color = Color\&.TRANSPARENT"

.PP
Definition at line 38 of file KeyFrame_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.KeyFrame_attributes\&.frame_point"

.PP
Definition at line 36 of file KeyFrame_attributes\&.java\&.
.SS "String com\&.video_browser_thesis\&.elements\&.KeyFrame_attributes\&.image_source"

.PP
Definition at line 35 of file KeyFrame_attributes\&.java\&.
.SS "Bitmap com\&.video_browser_thesis\&.elements\&.KeyFrame_attributes\&.video_img"

.PP
Definition at line 37 of file KeyFrame_attributes\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
