.TH "com.video_browser_thesis.adapters.Keyframe_ListAdapter" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.adapters.Keyframe_ListAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAdapter< Video_attributes >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVideoListHolder\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyframe_ListAdapter\fP (Context context, \fBVideo_attributes\fP[] video_attr)"
.br
.ti -1c
.RI "View \fBgetView\fP (int position, View convertView, ViewGroup parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Constructs a Keyframe Video Adapter which extends a Custom List Adapter 
.PP
\fBAuthor:\fP
.RS 4
Anshul Saini 
.RE
.PP
\fBVersion:\fP
.RS 4
5 
.RE
.PP

.PP
Definition at line 38 of file Keyframe_ListAdapter\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.video_browser_thesis\&.adapters\&.Keyframe_ListAdapter\&.Keyframe_ListAdapter (Contextcontext, \fBVideo_attributes\fP[]video_attr)"

.PP
Definition at line 44 of file Keyframe_ListAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "View com\&.video_browser_thesis\&.adapters\&.Keyframe_ListAdapter\&.getView (intposition, ViewconvertView, ViewGroupparent)"
Inflates the gallery item with different types of views\&. 
.PP
Definition at line 55 of file Keyframe_ListAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
