.TH "com.video_browser_thesis.processing.Processing" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.video_browser_thesis.processing.Processing \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcom\&.video_browser_thesis\&.processing\&.CB_GalleryProcessing\fP, \fBcom\&.video_browser_thesis\&.processing\&.CB_Processing\fP, \fBcom\&.video_browser_thesis\&.processing\&.KeyFrameList_Processing\fP, and \fBcom\&.video_browser_thesis\&.processing\&.MainGalleryProcessing\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetArrayContents\fP ()"
.br
.ti -1c
.RI "ArrayList< HashMap< String, 
.br
String > > \fBjsonFeed\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Processing\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "ArrayList<HashMap<String, String> > com\&.video_browser_thesis\&.processing\&.Processing\&.jsonFeed ()"

.SS "void com\&.video_browser_thesis\&.processing\&.Processing\&.setArrayContents ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
