.TH "SUBMITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/customGallery/gen/com/video_browser_thesis/activities/R.java" 3 "Thu Nov 22 2012" "Version 6.0" "Video Browser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SUBMITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT/customGallery/gen/com/video_browser_thesis/activities/R.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.attr\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.color\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.dimen\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.drawable\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.id\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.layout\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.string\fP"
.br
.ti -1c
.RI "class \fBcom\&.video_browser_thesis\&.activities\&.R\&.style\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.video_browser_thesis\&.activities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Video Browser from the source code\&.
